/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerbsRouteImport } from './routes/verbs'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizIndexRouteImport } from './routes/quiz.index'
import { Route as QuizTypingRouteImport } from './routes/quiz.typing'
import { Route as QuizMultipleChoiceRouteImport } from './routes/quiz.multiple-choice'
import { Route as QuizMatchingRouteImport } from './routes/quiz.matching'
import { Route as QuizFlashcardsRouteImport } from './routes/quiz.flashcards'

const VerbsRoute = VerbsRouteImport.update({
  id: '/verbs',
  path: '/verbs',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuizRoute,
} as any)
const QuizTypingRoute = QuizTypingRouteImport.update({
  id: '/typing',
  path: '/typing',
  getParentRoute: () => QuizRoute,
} as any)
const QuizMultipleChoiceRoute = QuizMultipleChoiceRouteImport.update({
  id: '/multiple-choice',
  path: '/multiple-choice',
  getParentRoute: () => QuizRoute,
} as any)
const QuizMatchingRoute = QuizMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => QuizRoute,
} as any)
const QuizFlashcardsRoute = QuizFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => QuizRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quiz': typeof QuizRouteWithChildren
  '/verbs': typeof VerbsRoute
  '/quiz/flashcards': typeof QuizFlashcardsRoute
  '/quiz/matching': typeof QuizMatchingRoute
  '/quiz/multiple-choice': typeof QuizMultipleChoiceRoute
  '/quiz/typing': typeof QuizTypingRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/verbs': typeof VerbsRoute
  '/quiz/flashcards': typeof QuizFlashcardsRoute
  '/quiz/matching': typeof QuizMatchingRoute
  '/quiz/multiple-choice': typeof QuizMultipleChoiceRoute
  '/quiz/typing': typeof QuizTypingRoute
  '/quiz': typeof QuizIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quiz': typeof QuizRouteWithChildren
  '/verbs': typeof VerbsRoute
  '/quiz/flashcards': typeof QuizFlashcardsRoute
  '/quiz/matching': typeof QuizMatchingRoute
  '/quiz/multiple-choice': typeof QuizMultipleChoiceRoute
  '/quiz/typing': typeof QuizTypingRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/quiz'
    | '/verbs'
    | '/quiz/flashcards'
    | '/quiz/matching'
    | '/quiz/multiple-choice'
    | '/quiz/typing'
    | '/quiz/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/verbs'
    | '/quiz/flashcards'
    | '/quiz/matching'
    | '/quiz/multiple-choice'
    | '/quiz/typing'
    | '/quiz'
  id:
    | '__root__'
    | '/'
    | '/quiz'
    | '/verbs'
    | '/quiz/flashcards'
    | '/quiz/matching'
    | '/quiz/multiple-choice'
    | '/quiz/typing'
    | '/quiz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizRoute: typeof QuizRouteWithChildren
  VerbsRoute: typeof VerbsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verbs': {
      id: '/verbs'
      path: '/verbs'
      fullPath: '/verbs'
      preLoaderRoute: typeof VerbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/typing': {
      id: '/quiz/typing'
      path: '/typing'
      fullPath: '/quiz/typing'
      preLoaderRoute: typeof QuizTypingRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/multiple-choice': {
      id: '/quiz/multiple-choice'
      path: '/multiple-choice'
      fullPath: '/quiz/multiple-choice'
      preLoaderRoute: typeof QuizMultipleChoiceRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/matching': {
      id: '/quiz/matching'
      path: '/matching'
      fullPath: '/quiz/matching'
      preLoaderRoute: typeof QuizMatchingRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/flashcards': {
      id: '/quiz/flashcards'
      path: '/flashcards'
      fullPath: '/quiz/flashcards'
      preLoaderRoute: typeof QuizFlashcardsRouteImport
      parentRoute: typeof QuizRoute
    }
  }
}

interface QuizRouteChildren {
  QuizFlashcardsRoute: typeof QuizFlashcardsRoute
  QuizMatchingRoute: typeof QuizMatchingRoute
  QuizMultipleChoiceRoute: typeof QuizMultipleChoiceRoute
  QuizTypingRoute: typeof QuizTypingRoute
  QuizIndexRoute: typeof QuizIndexRoute
}

const QuizRouteChildren: QuizRouteChildren = {
  QuizFlashcardsRoute: QuizFlashcardsRoute,
  QuizMatchingRoute: QuizMatchingRoute,
  QuizMultipleChoiceRoute: QuizMultipleChoiceRoute,
  QuizTypingRoute: QuizTypingRoute,
  QuizIndexRoute: QuizIndexRoute,
}

const QuizRouteWithChildren = QuizRoute._addFileChildren(QuizRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizRoute: QuizRouteWithChildren,
  VerbsRoute: VerbsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
